### ISSUE TITLE
Its not working . After enrolling it identifies each and everyone with same name.

### ISSUE THREAD

**Issue by ayushsa** [rposbo/speaker-recognition-api#2]
It's not working. After enrolling it identifies each and everyone with the same name.

**Comment by raghavpatnecha** [comment]
Can't happen. I tried it. You should try this one [Voice Auth](https://github.com/raghavpatnecha/voice-authentication). It is built on he same service

**Comment by rposbo** [comment]
Hmmm, strange. That other repo uses the same js recorder code, so should function the same way. I'll investigate.
