### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by toddler4372** [rposbo/speaker-recognition-api#8]
Hi, I get this 404 error once in the demo after I record my voice. (screenshot) It records fine, and sounds fine on playback. Any ideas? The work you've done here is exactly the help I'm needing with the API, btw.
<img width="629" alt="Screen Shot 2021-03-19 at 12 36 17 PM" src="https://user-images.githubusercontent.com/10601383/111833898-0d147c00-88b0-11eb-8b0b-9275f8eb3bbc.png">

**Comment by rposbo** [comment]
What happens when you hit "list verification phrases"? If that shows a 404, then MS might have changed the API endpoints again and we'll need to update them in this demo.

Did you enter the correct value for your endpoint and key on the page prior?

**Comment by rposbo** [comment]
yep, CS API endpoints have changed :(

**Comment by rposbo** [comment]
Ah - you just need the domain part of your CS endpoint now, instead of, e.g.:

`https://<your cs name>.cognitiveservices.azure.com/sts/v1.0/issuetoken`

just use:

`https://<your cs name>.cognitiveservices.azure.com/`
