### ISSUE TITLE
navigator.getUserMedia is not a function on Localhost

### ISSUE THREAD

**Issue by toddler4372** [rposbo/speaker-recognition-api#9]
The identification works well on your secure site, but I get this error when testing locally when clicking "Create Identification Profile." I tried using navigator.mediaDevices.getUserMedia() instead but had the same error.
<img width="1675" alt="Screen Shot 2021-03-22 at 11 00 23 AM" src="https://user-images.githubusercontent.com/10601383/112036932-6d98f880-8afe-11eb-8463-e13d9547b147.png">

**Comment by toddler4372** [comment]
Nevermind, I was accessing the server via local IP, now works with http://localhost:8080/.

**Comment by rposbo** [comment]
yeah, I think you need to use https to access getUserMedia, _or_ localhost.
